[package]
name = "fizzyhex/baseline"
version = "0.2.2"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
description = "The best friend of your initializer scripts."
exclude = [
    "build",
    "docs",
    ".gitignore",
    "aftman.toml",
    "moonwave.toml",
    "README.md",
    "selene.toml"
]

[dependencies]
